import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface JourneyStep {
  step: number;
  counter: string;
  service: string;
  purpose: string;
  wait_minutes: number;
  documents: string[];
  tip: string;
}

export interface JourneyData {
  task_summary: string;
  total_minutes: number;
  journey: JourneyStep[];
}

export function generateJourneyPDF(data: JourneyData, token: string): void {
  const doc = new jsPDF();
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN');
  const timeStr = now.toLocaleTimeString('en-IN');

  // Header
  doc.setFillColor(10, 191, 163);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('DISHA — Union Bank of India', 14, 15);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Branch Visit Slip · ${dateStr} · ${timeStr}`, 14, 23);

  // Token + task
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Token: ${token || 'Walk-in'}`, 14, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Task: ${data.task_summary} · Est. ${data.total_minutes} minutes`, 14, 50);

  // Journey table
  autoTable(doc, {
    startY: 58,
    head: [['Step', 'Counter', 'Service', 'Wait (min)']],
    body: data.journey.map(s => [
      s.step.toString(),
      s.counter,
      s.service,
      `~${s.wait_minutes}`,
    ]),
    headStyles: { fillColor: [10, 191, 163] },
    styles: { fontSize: 10 },
    columnStyles: { 0: { cellWidth: 15 }, 3: { cellWidth: 25 } },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by DISHA · iDEA Hackathon 2.0', 14, pageHeight - 10);

  doc.save(`DISHA_Journey_${dateStr.replace(/\//g, '-')}.pdf`);
}

export function generateLoanPDF(
  profile: { cibil: number; income: number; loanAmount: number; loanType: string },
  reasons: Array<{ title: string; your_value: string; required: string; plain_explanation: string; quick_fix: string }>,
  plan: Array<{ month: number; theme: string; primary_action: string; secondary_action: string; expected_cibil_gain: number; milestone: string }>
): void {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(10, 191, 163);
  doc.rect(0, 0, 210, 25, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('DISHA — Loan Eligibility Report', 14, 16);

  // Customer profile
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text('Customer Profile', 14, 35);
  autoTable(doc, {
    startY: 39,
    body: [
      ['CIBIL Score', profile.cibil.toString()],
      ['Monthly Income', `₹${profile.income.toLocaleString('en-IN')}`],
      ['Loan Amount Requested', `₹${profile.loanAmount.toLocaleString('en-IN')}`],
      ['Loan Type', profile.loanType],
    ],
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
  });

  // Rejection reasons
  const afterProfile = (doc as any).lastAutoTable?.finalY + 10 || 90;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Rejection Reasons', 14, afterProfile);

  autoTable(doc, {
    startY: afterProfile + 4,
    head: [['Issue', 'Your Value', 'Required']],
    body: reasons.map(r => [r.title, r.your_value, r.required]),
    headStyles: { fillColor: [255, 107, 53] },
    styles: { fontSize: 9 },
  });

  // Recovery plan on new page
  doc.addPage();
  doc.setFillColor(10, 191, 163);
  doc.rect(0, 0, 210, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('Your 90-Day Recovery Plan', 14, 13);

  autoTable(doc, {
    startY: 28,
    head: [['Month', 'Theme', 'Primary Action', 'CIBIL Gain', 'Milestone']],
    body: plan.map(p => [
      `Month ${p.month}`,
      p.theme,
      p.primary_action,
      `+${p.expected_cibil_gain}`,
      p.milestone,
    ]),
    headStyles: { fillColor: [10, 191, 163] },
    styles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 18 }, 3: { cellWidth: 18 } },
  });

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('Generated by DISHA · iDEA Hackathon 2.0', 14, doc.internal.pageSize.height - 10);
  doc.save('DISHA_Loan_Plan.pdf');
}

export function generateBereavementPDF(
  steps: Array<{ step_number: number; title: string; description: string; documents_needed: string[]; counter: string; time_estimate: string }>,
  legalSummary: string,
  helpline: string
): void {
  const doc = new jsPDF();

  // Soft header
  doc.setFillColor(219, 234, 254);
  doc.rect(0, 0, 210, 25, 'F');
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text('DISHA — Your Banking Guide', 14, 16);

  let y = 36;
  steps.forEach(s => {
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Step ${s.step_number}: ${s.title}`, 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(s.description, 180);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 3;
    if (s.documents_needed.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Documents needed:', 14, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      s.documents_needed.forEach(d => {
        doc.text(`  • ${d}`, 14, y);
        y += 4;
      });
    }
    doc.setTextColor(100, 116, 139);
    doc.text(`Counter: ${s.counter} · ${s.time_estimate}`, 14, y);
    y += 8;
    doc.setTextColor(15, 23, 42);
    if (y > 260) { doc.addPage(); y = 20; }
  });

  // Legal summary
  doc.setFont('helvetica', 'bold');
  doc.text('Your Legal Rights:', 14, y + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const legalLines = doc.splitTextToSize(legalSummary, 180);
  doc.text(legalLines, 14, y + 10);
  y += legalLines.length * 5 + 20;

  // Helpline
  doc.setFillColor(219, 234, 254);
  doc.rect(10, y, 190, 16, 'F');
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(helpline, 14, y + 10);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by DISHA · iDEA Hackathon 2.0', 14, doc.internal.pageSize.height - 10);
  doc.save('DISHA_Bereavement_Guide.pdf');
}

export function generateSalaryPDF(
  salary: number,
  budget: { needs: { percentage: number; amount: number }; wants: { percentage: number; amount: number }; savings: { percentage: number; amount: number } },
  goals: Array<{ name: string; target: number; monthly_contribution: number; months_to_achieve: number }>,
  actions: string[]
): void {
  const doc = new jsPDF();

  doc.setFillColor(10, 191, 163);
  doc.rect(0, 0, 210, 25, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('DISHA — My Financial Plan', 14, 16);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.text(`Monthly Take-Home: ₹${salary.toLocaleString('en-IN')}`, 14, 35);

  autoTable(doc, {
    startY: 42,
    head: [['Category', 'Percentage', 'Amount (₹)']],
    body: [
      ['Needs (essentials)', `${budget.needs.percentage}%`, budget.needs.amount.toLocaleString('en-IN')],
      ['Wants (lifestyle)', `${budget.wants.percentage}%`, budget.wants.amount.toLocaleString('en-IN')],
      ['Savings & Goals', `${budget.savings.percentage}%`, budget.savings.amount.toLocaleString('en-IN')],
    ],
    headStyles: { fillColor: [10, 191, 163] },
    styles: { fontSize: 10 },
  });

  const afterBudget = (doc as any).lastAutoTable?.finalY + 10 || 90;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Your Goals', 14, afterBudget);

  autoTable(doc, {
    startY: afterBudget + 4,
    head: [['Goal', 'Target ₹', 'Monthly ₹', 'Timeline']],
    body: goals.map(g => [g.name, g.target.toLocaleString('en-IN'), g.monthly_contribution.toLocaleString('en-IN'), `${g.months_to_achieve} months`]),
    headStyles: { fillColor: [124, 92, 191] },
    styles: { fontSize: 9 },
  });

  const afterGoals = (doc as any).lastAutoTable?.finalY + 10 || 160;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('First Month Actions', 14, afterGoals);
  actions.forEach((a, i) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`${i + 1}. ${a}`, 14, afterGoals + 8 + i * 6);
  });

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('Generated by DISHA · iDEA Hackathon 2.0', 14, doc.internal.pageSize.height - 10);
  doc.save('DISHA_Financial_Plan.pdf');
}
